import "./globals.css";

export const metadata = {
  title: "AutoAuctionHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <main className='container mx-auto px-5 pt-10'>{children}</main>
      </body>
    </html>
  );
}
